"""`manamap pilot regen` — the fleet rebuild that did not exist.

A model change stales every deck's figures and there was no command to rebuild
them; the fetchland fix on 2026-08-30 was regenerated by a hand-written zsh loop
that broke twice on globbing before it ran.

MEASURED on the real fleet, 72 targets across six stages:

    goldfish stage, --jobs 1     83.6s
    goldfish stage, --jobs 8     23.7s      3.5x
    whole fleet,    --jobs 8    109.4s

and `git status data/` was EMPTY after each — the tracked artifacts were already
current, so byte-identical output is the bit-identity proof.
"""

import pytest

from manamap.pilot import regen


def test_stages_run_in_dependency_order():
    """NOT DECORATION. `mana_analysis` embeds goldfish figures, `net_change`
    reads the deck's diagnostic, `deck-info` composes everything. A later stage
    run against an earlier stage's stale output is the "measured against the
    wrong list" class this repo has already paid for.
    """
    order = list(regen.STAGE_NAMES)
    for earlier, later in (("goldfish", "mana-analysis"),
                           ("goldfish", "net-change"),
                           ("goldfish", "diagnose"),
                           ("diagnose", "deck-info"),
                           ("mana-analysis", "deck-info")):
        assert order.index(earlier) < order.index(later), f"{earlier} after {later}"


def test_every_stage_names_a_real_module_with_a_main():
    import importlib

    checked = 0
    for _stage, _artifact, module, _kwargs, _branch_only in regen.STAGES:
        assert callable(getattr(importlib.import_module(module), "main", None)), module
        checked += 1
    assert checked >= 6


def test_net_change_is_offered_for_branches_only():
    """`net-change` compares a branch AGAINST the deck, so there is nothing for
    it to say about the deck alone. Without the flag it would be planned for
    every deck and fail on all of them."""
    rows = {stage: found for stage, _m, _k, found in regen.plan()}
    if "net-change" not in rows:
        pytest.skip("no branch carries net_change.json")
    assert all(branch is not None for _slug, branch in rows["net-change"])
    # …and the control: a stage that is NOT branch-only does include decks.
    if "goldfish" in rows:
        assert any(branch is None for _slug, branch in rows["goldfish"])


def test_only_refuses_a_stage_it_does_not_have():
    with pytest.raises(SystemExit, match="unknown stage"):
        regen.main(type("A", (), {"only": ["glodfish"], "slug": None,
                                  "jobs": None, "dry_run": True})())


def test_only_accepts_every_stage_it_advertises():
    """The control for the test above: each advertised name must be usable."""
    for stage in regen.STAGE_NAMES:
        rows = regen.plan(only=[stage])
        assert all(r[0] == stage for r in rows)


def test_a_dry_run_writes_nothing(tmp_path, monkeypatch):
    """`--dry-run` is the first thing anyone will type at a command that
    rewrites 72 tracked files, so it had better be inert."""
    lines = []
    result = regen.run(dry_run=True, echo=lines.append)
    assert result["ran"] == 0 and not result["failures"]
    assert any("dry-run" in line for line in lines)


def test_slug_scopes_the_plan_to_one_deck():
    everything = regen.plan()
    if not everything:
        pytest.skip("no tracked artifacts")
    slug = everything[0][3][0][0]
    scoped = regen.plan(slug=slug)
    assert scoped, f"nothing planned for {slug}"
    for _stage, _module, _kwargs, found in scoped:
        assert {s for s, _b in found} == {slug}


def test_a_retired_deck_is_not_regenerated(monkeypatch):
    """A retired deck's artifacts are HISTORY, NOT CLAIMS — the same rule the
    freshness gates follow. Re-introducing the bug: make `is_retired` always
    False and a deck nobody will shuffle comes back into the plan."""
    everything = regen.plan()
    if not everything:
        pytest.skip("no tracked artifacts")
    planned = {s for _st, _m, _k, found in everything for s, _b in found}
    assert planned, "nothing planned at all"
    assert not any(regen.is_retired(s) for s in planned)

    monkeypatch.setattr(regen, "is_retired", lambda _slug: True)
    assert regen.plan() == [], "is_retired is not what scopes the plan"


def test_the_args_shim_reports_unset_flags_as_absent_not_as_an_error():
    """Producers read optional flags with `getattr(args, x, False)` but some
    read `args.x` directly; a shim that raised would fail deep inside a worker
    where the traceback is pickled and unhelpful."""
    args = regen._Args(slug="x", branch=None)
    assert args.slug == "x" and args.branch is None
    assert args.some_flag_nobody_set is None
