"""`manamap pilot regen` — the fleet rebuild that did not exist.

A model change stales every deck's figures and there was no command to rebuild
them; the fetchland fix on 2026-08-30 was regenerated by a hand-written zsh loop
that broke twice on globbing before it ran.

MEASURED on the real fleet, 72 targets across six stages:

    goldfish stage, --jobs 1     83.6s
    goldfish stage, --jobs 8     23.7s      3.5x
    whole fleet,    --jobs 8    109.4s

and `git status data/` was EMPTY after each — the tracked artifacts were already
current, so byte-identical output is the bit-identity proof.
"""

import json

import pytest

from manamap.pilot import regen


def test_stages_run_in_dependency_order():
    """NOT DECORATION. `mana_analysis` embeds goldfish figures, `net_change`
    reads the deck's diagnostic, `deck-info` composes everything. A later stage
    run against an earlier stage's stale output is the "measured against the
    wrong list" class this repo has already paid for.
    """
    order = list(regen.STAGE_NAMES)
    for earlier, later in (("goldfish", "mana-analysis"),
                           ("goldfish", "net-change"),
                           ("goldfish", "diagnose"),
                           ("diagnose", "deck-info"),
                           ("mana-analysis", "deck-info")):
        assert order.index(earlier) < order.index(later), f"{earlier} after {later}"


def test_every_stage_names_a_real_module_with_a_main():
    import importlib

    checked = 0
    for _stage, _artifact, module, _kwargs, _branch_only, _commander_only in regen.STAGES:
        assert callable(getattr(importlib.import_module(module), "main", None)), module
        checked += 1
    assert checked >= 6


@pytest.mark.regression
def test_net_change_is_offered_for_branches_only():
    """`net-change` compares a branch AGAINST the deck, so there is nothing for
    it to say about the deck alone. Without the flag it would be planned for
    every deck and fail on all of them."""
    rows = {stage: found for stage, _m, _k, found in regen.plan()}
    if "net-change" not in rows:
        pytest.skip("no branch carries net_change.json")
    assert all(branch is not None for _slug, branch in rows["net-change"])
    # …and the control: a stage that is NOT branch-only does include decks.
    if "goldfish" in rows:
        assert any(branch is None for _slug, branch in rows["goldfish"])


def test_only_refuses_a_stage_it_does_not_have():
    with pytest.raises(SystemExit, match="unknown stage"):
        regen.main(type("A", (), {"only": ["glodfish"], "slug": None,
                                  "jobs": None, "dry_run": True})())


def test_only_accepts_every_stage_it_advertises():
    """The control for the test above: each advertised name must be usable."""
    for stage in regen.STAGE_NAMES:
        rows = regen.plan(only=[stage])
        assert all(r[0] == stage for r in rows)


@pytest.mark.regression
def test_a_dry_run_writes_nothing(tmp_path, monkeypatch):
    """`--dry-run` is the first thing anyone will type at a command that
    rewrites 72 tracked files, so it had better be inert."""
    lines = []
    result = regen.run(dry_run=True, echo=lines.append)
    assert result["ran"] == 0 and not result["failures"]
    assert any("dry-run" in line for line in lines)


@pytest.mark.regression
def test_slug_scopes_the_plan_to_one_deck():
    everything = regen.plan()
    if not everything:
        pytest.skip("no tracked artifacts")
    slug = everything[0][3][0][0]
    scoped = regen.plan(slug=slug)
    assert scoped, f"nothing planned for {slug}"
    for _stage, _module, _kwargs, found in scoped:
        assert {s for s, _b in found} == {slug}


@pytest.mark.regression
def test_a_retired_deck_is_not_regenerated(monkeypatch):
    """A retired deck's artifacts are HISTORY, NOT CLAIMS — the same rule the
    freshness gates follow. Re-introducing the bug: make `is_retired` always
    False and a deck nobody will shuffle comes back into the plan."""
    everything = regen.plan()
    if not everything:
        pytest.skip("no tracked artifacts")
    planned = {s for _st, _m, _k, found in everything for s, _b in found}
    assert planned, "nothing planned at all"
    assert not any(regen.is_retired(s) for s in planned)

    monkeypatch.setattr(regen, "is_retired", lambda _slug: True)
    assert regen.plan() == [], "is_retired is not what scopes the plan"


def test_the_args_shim_reports_unset_flags_as_absent_not_as_an_error():
    """Producers read optional flags with `getattr(args, x, False)` but some
    read `args.x` directly; a shim that raised would fail deep inside a worker
    where the traceback is pickled and unhelpful."""
    args = regen._Args(slug="x", branch=None)
    assert args.slug == "x" and args.branch is None
    assert args.some_flag_nobody_set is None


@pytest.mark.regression
def test_regen_bootstraps_a_derived_artifact_it_is_missing():
    """A REFRESHER THAT CANNOT CREATE HIDES ITS OWN GAPS.

    `targets()` returned only places an artifact already existed, so a deck
    missing `diagnostic.json` was skipped by the `diagnose` stage forever and in
    silence — `deck-status` showed the file as a bare GATE with nothing saying
    why it never arrived. Two of the three PINNED decks were in exactly that
    state, so the dossier's vitals section and the cover sheet's engine-health
    word were absent on decks that are sleeved and played.

    Narrow on purpose: only artifacts derived purely from the deck's own
    committed inputs may be bootstrapped. Creating an authored or agent-written
    file would be the tool inventing a claim instead of recomputing one.
    """
    from manamap.config import DECKS_DIR
    from manamap.pilot import regen

    assert regen.BOOTSTRAP, "nothing bootstraps — the mechanism is inert"
    for artifact, needs in regen.BOOTSTRAP.items():
        assert artifact.endswith(".json"), artifact
        # The precondition must be a real, purely-derived input, so a deck that
        # is not yet measurable is not dragged into the plan.
        assert needs in ("goldfish_metrics.json", "cards.json"), needs

    got = dict.fromkeys(s for s, b in regen.targets("diagnostic.json") if b is None)
    checked = 0
    for deck in sorted(DECKS_DIR.iterdir()):
        if not deck.is_dir() or regen.is_retired(deck.name):
            continue
        if not (deck / "goldfish_metrics.json").exists():
            continue
        if not regen.is_pinned(deck.name):
            continue
        checked += 1
        assert deck.name in got, (
            f"{deck.name} is SLEEVED, can be diagnosed, and regen does not plan "
            f"it — the stage would skip it forever without saying so")
    assert checked >= 2


@pytest.mark.regression
def test_only_a_sleeved_deck_is_built_automatically():
    """SLEEVED IS BUILT; ON THE BENCH IS TRIGGERED BY HAND.

    A deck pinned in paper is one the pilot plays, so its measurements are kept
    complete automatically — that is what pinning means. A bench deck is
    malleable: it changes daily, nobody has claimed it exists in cardboard, and
    its stages run when the pilot asks. Bootstrapping there manufactures
    artifacts for a list that will be different tomorrow, and puts a freshness
    gate on work in progress.

    The first cut of `BOOTSTRAP` missed this and created `diagnostic.json` for
    three bench decks on its first run.

    A DECK THAT ALREADY HAS THE ARTIFACT IS STILL A BENCH DECK, and this used to
    skip those — which made the guard depend on the fleet happening to contain a
    bench deck with no diagnostic. On 2026-09-14 it stopped containing one:
    ingris-infect, the last example, was broken down for parts, and sharknado
    had a diagnostic because the pilot asked for one BY HAND, which is exactly
    what a bench deck is allowed to do. The guard then failed with "no bench
    deck to prove the exclusion against" — an unsatisfiable check reading as a
    broken invariant.

    Dropping the skip made it satisfiable, and the wording that came with it —
    "regen must leave a bench deck alone whether or not the artifact is already
    there" — was SUPERSEDED on 2026-09-26. It is now exactly the opposite where
    the artifact exists: a tracked file with a freshness test on it is refreshed
    on every live deck (see
    `test_the_sweep_refreshes_every_live_deck_that_already_has_the_artifact`).

    What this test still guards is the CREATION half, and it is guarded here by
    construction: no bench deck holds a `diagnostic.json`, and `bootstrappable`
    requires `is_pinned`, so neither route can put one there. If a pilot asks for
    one by hand the deck joins the refresh set, which is correct — the pilot
    decided the list deserved a tracked figure, and this tool does not.
    """
    from manamap.config import DECKS_DIR
    from manamap.pilot import regen

    planned = {s for s, b in regen.targets("diagnostic.json") if b is None}
    bench = 0
    for deck in sorted(DECKS_DIR.iterdir()):
        if not deck.is_dir() or regen.is_retired(deck.name):
            continue
        if regen.is_pinned(deck.name):
            continue
        bench += 1
        assert deck.name not in planned, (
            f"{deck.name} is on the bench and regen would build it a "
            f"diagnostic it never asked for")
    assert bench >= 1, "no bench deck to prove the exclusion against"


def test_a_branch_is_never_bootstrapped():
    """A branch is a candidate list. Creating a measurement it never asked for
    is work nobody ordered, and it would put a tracked artifact on a directory
    the pilot may delete tomorrow."""
    from manamap.pilot import regen

    for slug, branch in regen.targets("diagnostic.json"):
        if branch is None:
            continue
        from manamap.config import DECKS_DIR
        assert (DECKS_DIR / slug / "branches" / branch / "diagnostic.json").exists(), (
            f"{slug}@{branch} is planned for an artifact it does not have")


@pytest.mark.regression
def test_the_sweep_refreshes_every_live_deck_that_already_has_the_artifact():
    """WHATEVER IS GATED MUST BE SWEPT. The rule this replaced said the opposite.

    Until 2026-09-26 a bare `regen` touched sleeved decks only, on the stated
    grounds that rebuilding a bench deck's numbers "measures a list that will be
    different tomorrow" and would put "a freshness gate on work in progress".

    THE GATE WAS ALREADY THERE, and that is what settles it. `_slugs()` in
    `test_pilot_artifact_freshness` recomputes `goldfish_metrics.json`,
    `mana_analysis.json` and `info.json` for every live deck holding one —
    `emiel-blink` and `meren-recursion` included — and
    `test_the_fleet_is_stamped_with_the_model_that_is_running` checks every deck
    that is not retired. So the exclusion bought none of the protection its
    docstring described and cost real staleness: a prose edit to
    `MODEL_ASSUMPTIONS` moved `meta.model_version`, `regen` rebuilt 33 of 36
    goldfish artifacts, and the suite went red on the two bench decks it had
    skipped — then red a second time one stage down, on the `info.json` composed
    from those same goldfish figures.

    A tracked artifact with a freshness test on it cannot have "run it by hand"
    as its maintenance story.

    THE OTHER HALF IS UNCHANGED and lives in the two tests above: a MISSING
    artifact is still only created on a sleeved deck. Refresh and bootstrap are
    different questions, and answering them with one gate is what broke.
    """
    from manamap.config import DECKS_DIR
    from manamap.pilot import regen

    for artifact in ("goldfish_metrics.json", "mana_analysis.json", "info.json"):
        swept = {s for s, b in regen.targets(artifact) if b is None}
        assert swept, f"the sweep found nothing at all for {artifact}"

        live_with_artifact, bench_checked = set(), 0
        for deck in sorted(DECKS_DIR.iterdir()):
            if not deck.is_dir() or regen.is_retired(deck.name):
                continue
            if not (deck / artifact).exists():
                continue
            live_with_artifact.add(deck.name)
            if not regen.is_pinned(deck.name):
                bench_checked += 1
                assert deck.name in swept, (
                    f"{deck.name} is on the bench, already has {artifact}, and "
                    f"the sweep skipped it — so a model change leaves it stale "
                    f"and the freshness gate red with no command to fix it")

        assert swept == live_with_artifact, (
            f"the sweep for {artifact} does not match the set of live decks "
            f"holding one: swept-only={sorted(swept - live_with_artifact)}, "
            f"gated-only={sorted(live_with_artifact - swept)}")
        assert bench_checked >= 1, (
            f"no BENCH deck holds {artifact}, so this proves nothing — the "
            f"regression it guards needs one on disk")


@pytest.mark.regression
def test_a_retired_deck_is_still_never_swept_even_holding_the_artifact():
    """Widening the sweep to every LIVE deck must not widen it to a dead one.

    `is_retired` runs before every other check, and the seventeen artifacts in
    the fleet stamped at three older model versions are exactly these decks:
    broken-down and retired lists whose figures are frozen as published.
    Regenerating one would mean measuring a deck nobody will shuffle again.
    """
    from manamap.config import DECKS_DIR
    from manamap.pilot import regen

    swept = {s for s, _b in regen.targets("goldfish_metrics.json")}
    checked = 0
    for deck in sorted(DECKS_DIR.iterdir()):
        if not deck.is_dir() or not regen.is_retired(deck.name):
            continue
        if not (deck / "goldfish_metrics.json").exists():
            continue
        checked += 1
        assert deck.name not in swept, (
            f"{deck.name} is retired or broken down and the sweep would "
            f"re-measure a list nobody will shuffle")
    assert checked >= 1, "no retired deck with the artifact to prove this against"


@pytest.mark.regression
def test_naming_a_deck_is_the_manual_trigger_and_works_on_any_deck():
    """`--slug` must reach a BENCH deck, or the rule above becomes "you may
    never regenerate a deck you have not sleeved" — which is not the rule.

    The slug is passed THROUGH to `targets`, not applied as a filter over its
    result; filtering afterwards would make `regen --slug heliod` return nothing
    at all, silently doing nothing on an explicit instruction.
    """
    from manamap.config import DECKS_DIR
    from manamap.pilot import regen

    bench = [d.name for d in sorted(DECKS_DIR.iterdir())
             if d.is_dir() and not regen.is_retired(d.name)
             and not regen.is_pinned(d.name)
             and (d / "goldfish_metrics.json").exists()]
    if not bench:
        pytest.skip("no bench deck with metrics to name")
    slug = bench[0]
    named = {s for s, _b in regen.targets("goldfish_metrics.json", slug=slug)}
    assert slug in named, (
        f"`regen --slug {slug}` reaches nothing — naming a deck must override "
        f"the sleeved-only default, or the flag silently does nothing")
    rows = regen.plan(only=["goldfish"], slug=slug)
    # A named deck's BRANCHES ride along (ingris-infect carries three with
    # metrics); the deck itself must be there and nothing from another deck.
    assert rows and (slug, None) in rows[0][3], rows
    assert all(s == slug for s, _b in rows[0][3]), rows


@pytest.mark.regression
def test_an_archived_deck_is_never_swept_or_named_into_a_rebuild():
    """History is frozen. `is_retired` already excluded these; this pins it so a
    later change to the sleeved rule cannot quietly re-admit them."""
    from manamap.config import DECKS_DIR
    from manamap.pilot import regen

    checked = 0
    for deck in sorted(DECKS_DIR.iterdir()):
        if not deck.is_dir() or not regen.is_retired(deck.name):
            continue
        checked += 1
        assert not regen.targets("goldfish_metrics.json", slug=deck.name), (
            f"{deck.name} is archived and regen would still rebuild it")
    assert checked >= 2


# ── 60-card formats (2026-10-09): the commander-only stages are skipped and SAID ──

def _deck(decks, slug, fmt=None, artifacts=()):
    base = decks / slug
    base.mkdir(parents=True)
    doc = {"deck": slug, "decklist_sha256": "a" * 64,
           "cards": [{"name": "Forest", "quantity": 4, "type_line": "Basic Land — Forest"}]}
    if fmt:
        doc["format"] = fmt
    (base / "decklist.txt").write_text("4 Forest\n")
    (base / "cards.json").write_text(json.dumps(doc))
    for name in artifacts:
        (base / name).write_text("{}")
    return base


def test_the_plan_drops_the_commander_only_stages_for_a_60_card_deck_and_keeps_them_for_commander(
        tmp_path, monkeypatch):
    """The goldfish seats a commander and deals against a table, and `diagnose`,
    `benchmark` and `net-change` are readings of it. A Modern deck holding one of
    those files (a defect — nothing writes it) is dropped from the plan rather
    than regenerated; the Commander control with the same files keeps every
    stage. Re-introduce the bug by ignoring `commander_only` in `_plan` and the
    Modern deck comes back into the goldfish stage."""
    decks = tmp_path / "decks"
    monkeypatch.setattr("manamap.config.DECKS_DIR", decks)
    both = ("goldfish_metrics.json", "mana_analysis.json", "combos.json", "info.json")
    _deck(decks, "cmdr", artifacts=both)
    _deck(decks, "elvesish", fmt="modern", artifacts=both)

    planned = {stage: {s for s, _b in found} for stage, _m, _k, found in regen.plan()}
    assert planned["goldfish"] == {"cmdr"}, planned
    for stage in ("mana-analysis", "deck-combos", "deck-info"):
        assert planned[stage] == {"cmdr", "elvesish"}, (stage, planned)
    assert regen.COMMANDER_ONLY_STAGES == {"goldfish", "net-change", "diagnose", "benchmark"}

    # The skips are NAMED, per stage, with the format — never inferred from a
    # stage that is quietly absent from the plan.
    skips = regen.skipped()
    assert ("goldfish", "elvesish", "Modern") in skips
    assert all(s == "elvesish" for _st, s, _f in skips), skips
    assert {st for st, _s, _f in skips} == regen.COMMANDER_ONLY_STAGES
    # …and `--slug` scopes the skips the way it scopes the plan.
    assert regen.skipped(slug="cmdr") == []


def test_a_dry_run_echoes_the_skip_with_the_format_named(tmp_path, monkeypatch):
    decks = tmp_path / "decks"
    monkeypatch.setattr("manamap.config.DECKS_DIR", decks)
    _deck(decks, "elvesish", fmt="modern", artifacts=("mana_analysis.json",))
    lines = []
    result = regen.run(slug="elvesish", dry_run=True, echo=lines.append)
    assert "  SKIPPED goldfish elvesish — not modelled for Modern" in lines
    assert "  SKIPPED net-change elvesish — not modelled for Modern" in lines
    assert any(line.strip() == "mana-analysis  (1)" for line in lines), lines
    assert result["ran"] == 0 and len(result["skipped"]) == len(regen.COMMANDER_ONLY_STAGES)


def test_regen_and_deck_status_agree_the_goldfish_is_commander_only():
    """Two registries — regen names PRODUCERS, deck_status names LIFECYCLE
    STEPS — so the one stage they both carry must sit in both sets."""
    from manamap.pilot import deck_status

    assert "goldfish" in regen.COMMANDER_ONLY_STAGES
    assert "goldfish" in deck_status.COMMANDER_ONLY_STAGES
    assert "benchmark" in regen.COMMANDER_ONLY_STAGES and "benchmark" in deck_status.COMMANDER_ONLY_STAGES
