"""The test suite's own measurements: counts, time, skips and coverage, dated.

`make test-report` runs both tiers with nothing served from the cache and under
coverage, each with `--record-run` (`tests/report_plugin.py`), then calls `record`
here. Everything a reader is told about the suite is computed in this file; the
`test-debrief` agent writes prose over the finding ids `diff` returns and never
produces a figure of its own (`.claude/skills/test-report/SKILL.md`).

    python -m manamap.suite_report preflight [--collect]   is the harness ready?
    python -m manamap.suite_report record DIR              raw runs -> data/test_reports/
    python -m manamap.suite_report diff [A B]              findings, latest vs previous
    python -m manamap.suite_report render [--write-docs]   the block in docs/testing.md

THE REPORT is facts only — `data/test_reports/<date>-<sha8>.json`, tracked. A
comparison is never stored: `diff` recomputes it from two reports, so a report can
never disagree with the run it describes. Per-test rows stay in the raw files
(`.pytest_cache/`); the tracked report keeps per-file roll-ups, the slowest tests and
every test that did not pass, which is what a diff needs at a size git can carry.

Two runs compare on WALL TIME only when both were uncached and both instrumented
alike — coverage costs time, and a cached run measures the cache. A finding says
"not comparable" rather than print a delta that means nothing.
"""
import argparse
import json
import os
import platform
import re
import subprocess
import sys
from collections import Counter
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
REPORTS = REPO / "data" / "test_reports"
TESTING_MD = REPO / "docs" / "testing.md"
SCHEMA = 1

#: The tiers `make test-report` records, in order, with the raw file each writes
#: (`integration` is not measured: a browser's time is not the suite's, and
#: coverage of `src/` says nothing about a rendered page).
TIERS = ("unit", "regression")
#: Tier names a report written before the 2026-10-05 partition carries. Kept
#: readable, never compared with the new ones: a different partition is a
#: different instrument, so `diff` finds no tier in common and says so.
LEGACY_TIERS = ("fast", "fleet")

#: Files whose change moves the HARNESS rather than a test: a run either side of
#: one measures two different instruments.
HARNESS_FILES = ("tests/conftest.py", "tests/report_plugin.py", "pyproject.toml",
                 "Makefile", ".github/workflows/test.yml")

#: The cache's skip reason (tests/conftest.py CACHED_SKIP), matched by prefix.
CACHED_PREFIX = "cached: unchanged"

SLOWEST_N = 25
SKIP_REASONS_N = 15
#: A file's test time is a finding when it grows by both of these.
FILE_SLOWER_RATIO, FILE_SLOWER_SECONDS = 1.5, 5.0
#: A module's coverage is a finding when it moves by at least this many points.
MODULE_COVERAGE_POINTS = 2.0
LOWEST_COVERED_N = 10

BLOCK_BEGIN = "<!-- suite-report:begin (generated by `python -m manamap.suite_report render --write-docs`; do not edit) -->"
BLOCK_END = "<!-- suite-report:end -->"


def _git(*args):
    return subprocess.run(["git", *args], cwd=REPO, capture_output=True,
                          text=True, check=False).stdout.strip()


# ── record ──────────────────────────────────────────────────────────────


def _tier_rollup(raw):
    tests = raw["tests"]
    outcomes = Counter(t["outcome"] or "unknown" for t in tests.values())
    reasons = Counter(t["reason"] for t in tests.values()
                      if t["outcome"] == "skipped" and t["reason"])
    cached = sum(n for r, n in reasons.items() if r.startswith(CACHED_PREFIX))
    by_file = {}
    for nodeid, t in tests.items():
        f = by_file.setdefault(nodeid.split("::")[0], {"tests": 0, "seconds": 0.0})
        f["tests"] += 1
        f["seconds"] += t["duration"]
    slowest = sorted(tests.items(), key=lambda kv: -kv[1]["duration"])[:SLOWEST_N]
    return {
        "markexpr": raw["markexpr"],
        "no_test_cache": raw["no_test_cache"],
        "instrumented": raw["instrumented"],
        "exitstatus": raw["exitstatus"],
        "collected": raw["collected"],
        "wall_seconds": raw["wall_seconds"],
        "test_seconds": round(sum(t["duration"] for t in tests.values()), 2),
        "outcomes": dict(sorted(outcomes.items())),
        "cached": cached,
        "skip_reasons": [[r, n] for r, n in reasons.most_common(SKIP_REASONS_N)],
        "not_passed": sorted([k, t["outcome"]] for k, t in tests.items()
                             if t["outcome"] in ("failed", "error", "xpassed")),
        "slowest": [[k, round(t["duration"], 2)] for k, t in slowest],
        "by_file": {k: {"tests": v["tests"], "seconds": round(v["seconds"], 2)}
                    for k, v in sorted(by_file.items())},
    }


def _coverage_rollup(path):
    """The coverage.py JSON report -> totals and a per-module percent."""
    cov = json.loads(Path(path).read_text())
    totals = cov["totals"]
    by_module = {}
    for name, f in cov["files"].items():
        rel = Path(name)
        rel = rel.relative_to(REPO) if rel.is_absolute() else rel
        by_module[str(rel)] = round(f["summary"]["percent_covered"], 1)
    return {
        "percent": round(totals["percent_covered"], 2),
        "statements": totals["num_statements"],
        "missing": totals["missing_lines"],
        "by_module": dict(sorted(by_module.items())),
    }


def _merge_raw(paths):
    """One tier measured in several pytest runs (`make regression` is a parallel
    run and then the fleet regen alone) -> one raw run: walls add, tests union,
    the worst exit status stands."""
    raws = [json.loads(p.read_text()) for p in paths]
    if len(raws) == 1:
        return raws[0]
    out = dict(raws[0])
    out["markexpr"] = " + ".join(r["markexpr"] for r in raws)
    out["collected"] = sum(r["collected"] for r in raws)
    out["wall_seconds"] = round(sum(r["wall_seconds"] for r in raws), 2)
    out["exitstatus"] = max((r["exitstatus"] for r in raws), key=lambda s: (s not in (0, 5), s))
    out["no_test_cache"] = all(r["no_test_cache"] for r in raws)
    out["instrumented"] = all(r["instrumented"] for r in raws)
    out["tests"] = {k: v for r in raws for k, v in r["tests"].items()}
    return out


def build(raw_dir, *, sha=None, today=None, dirty=None):
    """The tracked report from `make test-report`'s raw directory: `<tier>.json`,
    plus `<tier>.<step>.json` for a tier measured in more than one run."""
    raw_dir = Path(raw_dir)
    tiers = {}
    for tier in TIERS:
        files = sorted(raw_dir.glob(f"{tier}.json")) + sorted(raw_dir.glob(f"{tier}.*.json"))
        if files:
            tiers[tier] = _tier_rollup(_merge_raw(files))
    if not tiers:
        raise SystemExit(f"no raw runs in {raw_dir} (expected {', '.join(TIERS)}.json)")
    coverage = {}
    for key, name in (("unit", "coverage-unit.json"), ("combined", "coverage.json")):
        if (raw_dir / name).exists():
            coverage[key] = _coverage_rollup(raw_dir / name)
    # A full report keeps the per-module table on the combined run only; a
    # unit-scope report has nothing else, so its unit table stays.
    if "unit" in coverage and "combined" in coverage:
        coverage["unit"].pop("by_module")
    return {
        "schema": SCHEMA,
        "scope": "full" if "regression" in tiers else "unit",
        "date": (today or date.today()).isoformat(),
        "sha": sha or _git("rev-parse", "HEAD"),
        "dirty": (bool(_git("status", "--porcelain", "--", "src", "tests"))
                  if dirty is None else dirty),
        "machine": {"python": platform.python_version(), "platform": sys.platform,
                    "cpus": os.cpu_count()},
        "tiers": tiers,
        "coverage": coverage or None,
    }


#: What a report measured. `unit` is the default `make test-report` (~2 min);
#: `full` adds regression (`FULL=1`). Two scopes never compare: a unit report's
#: coverage would read as a 20-point drop against a full one. A report from
#: before scopes existed measured both tiers, so it reads as `full`.
SCOPES = ("unit", "full")


def scope_of(report):
    return report.get("scope", "full")


def report_name(report):
    suffix = "" if scope_of(report) == "full" else f".{scope_of(report)}"
    return f"{report['date']}-{report['sha'][:8]}{suffix}.json"


def history(directory=REPORTS, scope=None):
    """Every tracked report, oldest first (the name sorts by date), optionally
    only those of one scope."""
    paths = sorted(Path(directory).glob("*.json"))
    if scope is None:
        return paths
    return [p for p in paths if scope_of(json.loads(p.read_text())) == scope]


def _main_coverage(report):
    """The coverage a report's figures are about: both tiers for a full report,
    the unit tier for a unit one."""
    cov = report.get("coverage") or {}
    return cov.get("combined") or cov.get("unit")


# ── diff: the findings ──────────────────────────────────────────────────


def _comparable(a, b):
    return (a["no_test_cache"] and b["no_test_cache"]
            and a["instrumented"] == b["instrumented"])


def findings(cur, prev=None, *, harness_changed=None):
    """Every finding the debrief may cite, each with a stable id and its figures.

    `harness_changed` is the list of HARNESS_FILES that moved between the two
    reports' commits (computed by `diff` from git; passed in so this is pure)."""
    out = []

    def add(fid, kind, text, **figures):
        out.append({"id": fid, "kind": kind, "text": text, "figures": figures})

    for tier, t in cur["tiers"].items():
        for nodeid, outcome in t["not_passed"]:
            add(f"{tier}:{outcome}:{nodeid}", outcome, f"{nodeid} {outcome} ({tier})",
                tier=tier, nodeid=nodeid)
        if t["exitstatus"] not in (0, 5):
            add(f"{tier}:exit", "exit", f"the {tier} tier exited {t['exitstatus']}",
                tier=tier, exitstatus=t["exitstatus"])
        if t["cached"] and not t["no_test_cache"]:
            add(f"{tier}:cached", "cached",
                f"{t['cached']} {tier} test(s) were served from the cache, so this "
                f"run's time and coverage under-count them", tier=tier, cached=t["cached"])

    main_cov = _main_coverage(cur)
    if main_cov and "by_module" in main_cov:
        lowest = sorted(main_cov["by_module"].items(), key=lambda kv: kv[1])
        add("coverage:lowest", "coverage-lowest",
            f"the {LOWEST_COVERED_N} least-covered modules",
            modules=lowest[:LOWEST_COVERED_N])

    if prev is None:
        # A FIRST report still gets ids to cite (found by test-debrief's first
        # reading): the absolute figures, with nothing to compare against.
        for tier, t in cur["tiers"].items():
            add(f"{tier}:wall", "wall-absolute",
                f"{tier} wall {t['wall_seconds']:.0f}s, {t['test_seconds']:.0f}s in tests "
                f"(no previous report)", tier=tier, wall=t["wall_seconds"],
                in_tests=t["test_seconds"], collected=t["collected"])
        if main_cov:
            c = main_cov
            add("coverage:total", "coverage-absolute",
                f"coverage {c['percent']:.2f}% (no previous report)",
                percent=c["percent"], statements=c["statements"], missing=c["missing"])
        return out

    if harness_changed:
        add("harness:changed", "harness",
            "the harness changed between the two reports, so a delta may be the "
            "instrument, not the suite", files=harness_changed)

    for tier, t in cur["tiers"].items():
        p = prev["tiers"].get(tier)
        if p is None:
            add(f"{tier}:new-tier", "tier-not-comparable",
                f"the previous report has no {tier} tier (tiers "
                f"{', '.join(prev['tiers'])}): nothing to compare it with",
                tier=tier, previous_tiers=sorted(prev["tiers"]))
            continue
        if t["collected"] != p["collected"]:
            files = set(t["by_file"]) | set(p["by_file"])
            moved = sorted(
                [f, p["by_file"].get(f, {}).get("tests", 0),
                 t["by_file"].get(f, {}).get("tests", 0)] for f in files
                if p["by_file"].get(f, {}).get("tests", 0)
                != t["by_file"].get(f, {}).get("tests", 0))
            add(f"{tier}:count", "count",
                f"{tier} collected {p['collected']} -> {t['collected']}",
                tier=tier, before=p["collected"], after=t["collected"], files=moved)
        if _comparable(t, p):
            add(f"{tier}:wall", "wall",
                f"{tier} wall {p['wall_seconds']:.0f}s -> {t['wall_seconds']:.0f}s",
                tier=tier, before=p["wall_seconds"], after=t["wall_seconds"],
                delta=round(t["wall_seconds"] - p["wall_seconds"], 2))
            slower = []
            for f, row in t["by_file"].items():
                before = p["by_file"].get(f, {}).get("seconds")
                if (before and row["seconds"] >= before * FILE_SLOWER_RATIO
                        and row["seconds"] - before >= FILE_SLOWER_SECONDS):
                    slower.append([f, before, row["seconds"]])
            if slower:
                add(f"{tier}:slower-files", "slower",
                    f"{len(slower)} {tier} file(s) slowed by >={FILE_SLOWER_RATIO}x "
                    f"and >={FILE_SLOWER_SECONDS:.0f}s", tier=tier, files=sorted(slower))
        else:
            add(f"{tier}:wall", "wall-not-comparable",
                f"{tier} wall time is not comparable (cache or coverage differ)",
                tier=tier)
        before_r, after_r = dict(map(tuple, p["skip_reasons"])), dict(map(tuple, t["skip_reasons"]))
        moved = sorted([r, before_r.get(r, 0), n] for r, n in after_r.items()
                       if n > before_r.get(r, 0) and not r.startswith(CACHED_PREFIX))
        if moved:
            add(f"{tier}:skips", "skips", f"{tier} skip reasons that grew",
                tier=tier, reasons=moved)

    pc = _main_coverage(prev)
    if scope_of(cur) != scope_of(prev):
        add("scope:differs", "scope-not-comparable",
            f"a {scope_of(cur)} report against a {scope_of(prev)} one: coverage "
            f"is not compared", current=scope_of(cur), previous=scope_of(prev))
        pc = None
    if main_cov and pc and "by_module" in main_cov and "by_module" in pc:
        c = main_cov
        add("coverage:total", "coverage",
            f"coverage {pc['percent']:.2f}% -> {c['percent']:.2f}%",
            before=pc["percent"], after=c["percent"],
            delta=round(c["percent"] - pc["percent"], 2))
        moved = sorted(
            [m, pc["by_module"].get(m), v] for m, v in c["by_module"].items()
            if m not in pc["by_module"]
            or abs(v - pc["by_module"][m]) >= MODULE_COVERAGE_POINTS)
        if moved:
            add("coverage:modules", "coverage-modules",
                f"modules whose coverage moved >= {MODULE_COVERAGE_POINTS} points "
                f"(or are new)", modules=moved)
    return out


def _harness_changed(prev, cur):
    if prev["sha"] == cur["sha"]:
        return []
    names = _git("diff", "--name-only", prev["sha"], cur["sha"], "--", *HARNESS_FILES)
    return sorted(n for n in names.splitlines() if n)


def diff(cur_path=None, prev_path=None):
    """Findings for the latest report against the previous one OF THE SAME SCOPE
    (or two named)."""
    reports = history()
    if cur_path is None:
        if not reports:
            raise SystemExit("no reports in data/test_reports/ — run `make test-report`")
        cur_path = reports[-1]
        same = history(scope=scope_of(json.loads(cur_path.read_text())))
        same = [p for p in same if p != cur_path]
        prev_path = same[-1] if same else None
    cur = json.loads(Path(cur_path).read_text())
    prev = json.loads(Path(prev_path).read_text()) if prev_path else None
    return {
        "report": str(Path(cur_path).relative_to(REPO) if Path(cur_path).is_absolute() else cur_path),
        "previous": (str(Path(prev_path).relative_to(REPO)
                         if Path(prev_path).is_absolute() else prev_path)
                     if prev_path else None),
        "findings": findings(cur, prev,
                             harness_changed=_harness_changed(prev, cur) if prev else None),
    }


# ── render: the block in docs/testing.md ────────────────────────────────


def _mmss(seconds):
    m, s = divmod(int(round(seconds)), 60)
    return f"{m}:{s:02d}"


def render(report):
    lines = [BLOCK_BEGIN, "",
             f"Measured {report['date']} at `{report['sha'][:8]}`"
             f"{' (uncommitted changes in src/ or tests/)' if report['dirty'] else ''}, "
             f"{report['machine']['cpus']} CPUs, Python {report['machine']['python']}, "
             f"by `make test-report` — the tracked record is "
             f"`data/test_reports/{report_name(report)}`.", "",
             "| tier | collected | passed | skipped | xfailed | failed | wall | in tests |",
             "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for tier, t in report["tiers"].items():
        o = t["outcomes"]
        flags = ", ".join(f for f, on in (("uncached", t["no_test_cache"]),
                                          ("under coverage", t["instrumented"])) if on)
        lines.append(
            f"| {tier}{f' ({flags})' if flags else ''} | {t['collected']:,} | "
            f"{o.get('passed', 0):,} | {o.get('skipped', 0):,} | {o.get('xfailed', 0)} | "
            f"{o.get('failed', 0) + o.get('error', 0)} | **{_mmss(t['wall_seconds'])}** | "
            f"{_mmss(t['test_seconds'])} |")
    cov = report.get("coverage") or {}
    if cov:
        lines += [""]
        parts = []
        for key in ("unit", "fast"):   # "fast": a report from before the partition
            if key in cov:
                parts.append(f"the {key} tier alone **{cov[key]['percent']:.1f}%**")
        if "combined" in cov:
            c = cov["combined"]
            parts.append(f"both measured tiers **{c['percent']:.1f}%** of "
                         f"{c['statements']:,} statements in `src/manamap/` "
                         f"({c['missing']:,} never run)")
        lines.append("Line coverage: " + "; ".join(parts) + ".")
    slow = [s for t in report["tiers"].values() for s in t["slowest"]]
    slow.sort(key=lambda s: -s[1])
    lines += ["", "The five slowest tests: " + "; ".join(
        f"`{n.split('::')[-1]}` {s:.0f}s" for n, s in slow[:5]) + ".", "", BLOCK_END]
    return "\n".join(lines)


def write_docs(report, path=TESTING_MD):
    """Replace the generated block in docs/testing.md (the PROPOSAL: the working
    tree changes, nobody commits but the pilot)."""
    text = Path(path).read_text()
    block = render(report)
    if BLOCK_BEGIN in text:
        a = text.index(BLOCK_BEGIN)
        b = text.index(BLOCK_END, a) + len(BLOCK_END)
        text = text[:a] + block + text[b:]
    else:
        raise SystemExit(f"{path} has no `{BLOCK_BEGIN[:24]}...` block to replace")
    Path(path).write_text(text)


# ── preflight ───────────────────────────────────────────────────────────

#: A process that writes what the suite reads, or that fights it for the CPU.
#: The machine crashed twice with two heavy jobs together (PLAN, 2026-10-02).
COLLIDES = re.compile(r"pytest|manamap (?:run|train|pilot (?:regen|simulate|experiment|goldfish))"
                      r"|make (?:test|prepush|manuals)")


def _collect_count(markexpr):
    cmd = [sys.executable, "-m", "pytest", "--co", "-q", "-n0", "-p", "no:cacheprovider"]
    if markexpr is not None:
        cmd += ["-m", markexpr]
    res = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, check=False)
    m = re.search(r"(\d+)(?:/\d+)? tests? (?:collected|selected)", res.stdout)
    if m:
        return int(m.group(1))
    # `addopts` already carries `-q`, so this is `-qq`: pytest prints one
    # `path: N` line per file and no summary (found by test-preflight's first run).
    per_file = re.findall(r"^\S+\.py: (\d+)$", res.stdout, re.M)
    return sum(map(int, per_file)) if per_file else None


def preflight(collect=False):
    """Is the harness ready for a measured run? Facts, no verdict — the
    `test-preflight` agent reads them."""
    me = os.getpid()
    ps = subprocess.run(["ps", "-axo", "pid=,command="], capture_output=True,
                        text=True, check=False).stdout
    running = []
    for line in ps.splitlines():
        pid, _, cmd = line.strip().partition(" ")
        if pid.isdigit() and int(pid) not in (me, os.getppid()) \
                and COLLIDES.search(cmd) and "suite_report" not in cmd:
            running.append([int(pid), cmd[:160]])
    plugins = {}
    for mod in ("xdist", "pytest_cov", "coverage"):
        try:
            __import__(mod)
            plugins[mod] = True
        except ImportError:
            plugins[mod] = False
    reports = history()
    last = None
    if reports:
        r = json.loads(reports[-1].read_text())
        head = _git("rev-parse", "HEAD")
        last = {"path": str(reports[-1].relative_to(REPO)), "date": r["date"],
                "sha": r["sha"],
                "commits_since": int(_git("rev-list", "--count", f"{r['sha']}..HEAD") or 0),
                "harness_changed_since": _harness_changed(r, {"sha": head})}
    # `split`, not `[3:]`: `_git` strips, which eats the first line's status column.
    dirty = [l.split(maxsplit=1)[1]
             for l in _git("status", "--porcelain", "--", "src", "tests").splitlines()]
    out = {
        "head": _git("rev-parse", "HEAD"),
        "running": running,
        "plugins": plugins,
        "dirty_src_or_tests": dirty,
        "last_report": last,
        "docs_block_present": BLOCK_BEGIN in TESTING_MD.read_text(),
    }
    if collect:
        out["collected"] = {"unit": _collect_count(None),
                            "regression": _collect_count("regression"),
                            "integration": _collect_count("integration"),
                            "everything": _collect_count("")}
    return out


# ── CLI ─────────────────────────────────────────────────────────────────


def main(argv=None):
    ap = argparse.ArgumentParser(prog="python -m manamap.suite_report",
                                 description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    pf = sub.add_parser("preflight", help="is the harness ready? (JSON)")
    pf.add_argument("--collect", action="store_true",
                    help="also count each tier by collecting it (~1 min)")
    rec = sub.add_parser("record", help="fold raw runs into data/test_reports/")
    rec.add_argument("raw_dir")
    df = sub.add_parser("diff", help="findings: latest report vs previous (JSON)")
    df.add_argument("reports", nargs="*", help="CURRENT [PREVIOUS]")
    rn = sub.add_parser("render", help="the docs/testing.md block for the latest report")
    rn.add_argument("--write-docs", action="store_true")
    args = ap.parse_args(argv)

    if args.cmd == "preflight":
        print(json.dumps(preflight(args.collect), indent=1))
    elif args.cmd == "record":
        report = build(args.raw_dir)
        REPORTS.mkdir(parents=True, exist_ok=True)
        path = REPORTS / report_name(report)
        path.write_text(json.dumps(report, indent=1) + "\n")
        print(f"wrote {path.relative_to(REPO)}")
        print(render(report))
        failed = [t for t, r in report["tiers"].items() if r["exitstatus"] not in (0, 5)]
        if failed:
            print(f"tier(s) failed: {', '.join(failed)}", file=sys.stderr)
            return 1
    elif args.cmd == "diff":
        print(json.dumps(diff(*args.reports[:2]), indent=1))
    elif args.cmd == "render":
        # The docs block is the latest FULL report: a unit-scope one would drop
        # the regression row every time someone asked for a quick reading.
        reports = history(scope="full")
        if not reports:
            raise SystemExit("no full report in data/test_reports/ — `make test-report FULL=1`")
        report = json.loads(reports[-1].read_text())
        if args.write_docs:
            write_docs(report)
            print(f"rewrote the block in {TESTING_MD.relative_to(REPO)}")
        else:
            print(render(report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
